name: Selenium Tests

on:
  push:
    branches:
      - main  # Adjust to your default branch
  pull_request:
    branches:
      - main  # This triggers the workflow when pull requests are opened or pushed to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Adjust to your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r selenium

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable  # Install Google Chrome
          sudo apt-get install -y chromedriver  # Install ChromeDriver

      - name: Run Selenium Tests
        run: |
          pytest  # Run your Selenium tests using pytest (adjust command if needed)
